### PR TITLE
Added doctests

### PR DESCRIPTION
**Pull request by astrofrog**
Replaces #20

### CODE REVIEW

**Comment by astrofrog** [comment]
To run the tests:

```
python test_examples_doctests.py
```

This uses the built-in doctest since the code examples almost conform to the doctest standard!

**Comment by astrofrog** [comment]
cc @cdeil

**Comment by cdeil** [comment]
Nice solution!

Much better to test the code in the paper directly instead of copy & pasting & slightly modifying them as I did.

**Comment by eteq** [comment]
Yeah, this is quite clever.  We can certainly adapt this to future papers, but @astrofrog and @cdeil, do you think this is worth the effort of generalizing it enough that it could be put in the astropy core, so that anyone who writes papers with code examples can use it? (I _don't_ think it's really worth it right now, but thought I'd ask.)

**Pull request merged**
