### PR TITLE
WIP: Add unit tests for all code examples

### PR DESCRIPTION
**Pull request by cdeil**
TODO:
- [ ] Finish `test_fig_5()`
- [ ] Finish `test_fig_6()`

@astrofrog At the moment I'm stuck with `test_fig_5()` because I don't know how to write a Table in `ipac` ascii format:

```
======================================================================
ERROR: test_examples.test_fig_5
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/deil/work/papers/astropy-v0.2-paper/examples/test_examples.py", line 117, in test_fig_5
    t.write('catalog.tbl', format='ascii', Writer=ascii.Ipac)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/astropy-0.3.dev4471-py2.7-macosx-10.8-intel.egg/astropy/io/registry.py", line 224, in write
    writer(data, *args, **kwargs)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/astropy-0.3.dev4471-py2.7-macosx-10.8-intel.egg/astropy/io/ascii/connect.py", line 25, in write_asciitable
    return write(table, filename, **kwargs)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/astropy-0.3.dev4471-py2.7-macosx-10.8-intel.egg/astropy/io/ascii/ui.py", line 280, in write
    lines = writer.write(table)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/astropy-0.3.dev4471-py2.7-macosx-10.8-intel.egg/astropy/io/ascii/ipac.py", line 91, in write
    raise NotImplementedError
NotImplementedError
```

### CODE REVIEW

**Comment by astrofrog** [comment]
About the IPAC writing - oops, it's not done yet, so the example should be changed to something 0.2-compatible.

**Comment by cdeil** [comment]
Actually the example only shows IPAC table reading, not writing.
Does reading work in 0.2?
In any case it might be better to change to something where reading / writing works for the example.

**Comment by astrofrog** [comment]
IPAC reading works in `v0.2`. I guess we could change to something that works for both (like HDF5) but I thought this way we could maximize the number of formats shown. What do you think?

**Comment by astrofrog** [comment]
By the way, I meant to say, thank you very much for doing this!!

Part of me thinks that once the paper is published, we should include these tests in astropy master to make sure that things are still reasonably compatible with the paper version if possible. This is just an idea though - @eteq, what do you think?

**Comment by eteq** [comment]
I think that makes sense, except that some of it may be broken in v0.3 with API changes.  If so, though, we can just remove those and try to keep everything working that doesn't have a good reason to be broken.

Along these lines, for future papers, I think we might want to consider using [pythontex](https://github.com/gpoore/pythontex).  That lets you actually run python code from the tex document and reproduces the output, so we could always be certain the paper accurately reflects the code (although it doesn't ensure the converse is true for future versions.)

**Comment by astrofrog** [comment]
@cdeil - the latest draft has an additional example in Figure 1, and I fixed the answer to the cosmology example that you pointed out previously.

**Comment by astrofrog** [comment]
We need to update this with the submitted examples - there are a couple of very minor changes that I can submit a pull request to your branch for. No rush though, we can even wait until we hear back from the journal/referee.

**Comment by astrofrog** [comment]
@cdeil - now that the paper is close to final submission, we should try and finalize this PR

**Comment by astrofrog** [comment]
I'm working on this today (just so we don't duplicate efforts)

**Comment by astrofrog** [comment]
Thanks for your work on this! I managed to find a way to run the tests using doctest and without copying the code from the examples - see #29

**Pull request closed without merging**
